### PR TITLE
`optimake serve`

### LINKED ISSUE #45: Suggestion: `optimake serve` option
This should make the JSONL file then launch the server locally (using mongomock or otherwise), optionally running the `optimade-validator` on it.

### PR DESCRIPTION
**Pull request by eimrek**
resolves #45

This PR adds the `optimake serve` command that

1) (Optionally) converts a raw data archive into `optimade.jsonl`;
2) starts an OPTIMADE API with mongomock, ingesting the `optimade.jsonl`.

Uses the `insert_from_jsonl` feature from the PR https://github.com/Materials-Consortia/optimade-python-tools/pull/2094

Couple of comments:
* I thinking how i could pass in an optimade config to the API "directly", but i don't think that's possible currently, if i just want to directly use the `optimade-python-tools` server. I ended up just passing the config through environment variables. 
* In the config, i need to pass the custom provider fields, that i currently read from the JSONL file. I am wondering if this would make sense to do in `optimade-python-tools` instead, considering we're passing in the jsonl anyways.
* todo: tests

Note: I also changed the default `optimake` command to `optimake convert`.

@ml-evs does this approach make sense? if you agree, i'll try to think how to add tests for this as well.

### CODE REVIEW

**Review by ml-evs — COMMENTED** [review]
Like the approach so far @eimrek! Env vars is probably the way to go for server config for now, but we could definitely make that easier on the o-p-t side (e.g., add passable config objects everywhere that default to the global one).

Am I okay to merge https://github.com/Materials-Consortia/optimade-python-tools/pull/2094 now then? Can do a release too so its easier for you to test out.

**Comment by ml-evs** [comment]
I just merged and released https://github.com/Materials-Consortia/optimade-python-tools/pull/2094 if you want to try it out @eimrek! Added a few tests and made it slightly more ergonomic (allow absolute and relative paths etc), but it should allow for the same invocation as before.

**Comment by eimrek** [comment]
thanks @ml-evs, will have a test run soon.

But just to double-check, would it make sense to add something like https://github.com/materialscloud-org/optimade-maker/blob/556fecc02f3ffa3bce99aa00677e4acb7e952a5d/src/optimake/serve.py#L46

to optimade python tools instead?

Basically, just so if you pass in a jsonl file, it also takes the provider fields from there. And possibly ignores the provider fields from the config files.

Happy to move this to o-p-t, if there is a clear way to do it.

**Comment by ml-evs** [comment]
> thanks @ml-evs, will have a test run soon.
> 
> But just to double-check, would it make sense to add something like https://github.com/materialscloud-org/optimade-maker/blob/556fecc02f3ffa3bce99aa00677e4acb7e952a5d/src/optimake/serve.py#L46
> 
> to optimade python tools instead?
> 
> Basically, just so if you pass in a jsonl file, it also takes the provider fields from there. And possibly ignores the provider fields from the config files.
> 
> Happy to move this to o-p-t, if there is a clear way to do it.

Yeah I think we can consider that now, just didn't want to hold you up on this PR. It would be doable, but I think essentially the JSONL loading process will have to update the global CONFIG object for this to work smoothly for now. I can have a play around with it too.

**Pull request merged**
